import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "./CreateGIN.css";
import ModuleNavbar from "../../../../components/ModuleNavbar/ModuleNavbar";
import { API_URL } from "../../../../config";
import useSiteOptions from "../../../../hooks/useSiteOptions";

/*
  CreateGIN  →  Module: "Inventory"  |  Business Entity: "Inward"
  ─────────────────────────────────────────────────────────────────
  GIN No is generated by calling POST /api/create-document-sequence
  with module="Inventory", businessEntity="Inward".
  The backend returns { generatedCode } which becomes the ginNo.
*/

const blankItem = (sNo) => ({
  sNo,
  insertBags:    "",
  itemRate:      "",
  transactionNo: "",
  partyName:     "",
  broker:        "",
  itemCode:      "",
  itemName:      "",
  uom:           "",
  salesThrough:  "",
  _checked:      false,
});

const DEFAULT_ROWS = 1;

const CreateGIN = () => {
  const navigate = useNavigate();
  const [loading,      setLoading]      = useState(false);
  const [insertCount,  setInsertCount]  = useState(1);

  /* ── Sites filtered to Inventory / Inward ── */
  const { sites: siteOptions, loading: sitesLoading } =
    useSiteOptions("Inventory", "Inward");

  /* ── Transaction categories from Transaction Master (Inventory / Inward) ── */
  const [transactionCategories, setTransactionCategories] = useState([]);

  const [form, setForm] = useState({
    ginNo:               "",
    poCpoNo:             "",
    status:              "Open",
    site:                "",
    ginDate:             "",
    ginDescription:      "",
    ginType:             "Domestic",
    deliveryMode:        "By Road",
    transactionCategory: "",
    vendorCode:          "",
    vendorName:          "",
    manufacturerAddress: "",
    vehicleEntry:        "Inward",
    manufacturerCode:    "",
    manufacturerName:    "",
    vehicleNo:           "",
    challanInvoiceNo:    "",
    challanDate:         "",
    billDate:            "",
    ewayDate:            "",
    remarks:             "",
    comments:            "",
  });

  const [items, setItems] = useState(
    Array.from({ length: DEFAULT_ROWS }, (_, i) => blankItem(i + 1))
  );

  /* ── Fetch GIN No from DocumentSequence API + set default dates ── */
  useEffect(() => {
    const today = new Date().toISOString().split("T")[0];

    const fetchGinNo = async () => {
      try {
        /* Look up existing sequences for Inventory / Inward to get the next increment */
        const listRes  = await axios.get(`${API_URL}/api/document-sequence`);
        const matching = listRes.data.filter(
          (r) => r.module === "Inventory" && r.businessEntity === "Inward"
        );

        /* Determine next increment number */
        const nextIncrement = matching.length > 0
          ? Math.max(...matching.map((r) => Number(r.incrementNo))) + 1
          : 1;

        /* Determine the sequenceFormat saved for this entity (use last record's format, or default) */
        const lastRecord = matching.sort((a, b) =>
          new Date(b.createdAt) - new Date(a.createdAt)
        )[0];
        const sequenceFormat = lastRecord?.sequenceFormat || "dd/mm/yyyy";

        /* Build the GIN No locally (same logic as backend buildDatePart) */
        const d     = new Date();
        const dd    = String(d.getDate()).padStart(2, "0");
        const mm    = String(d.getMonth() + 1).padStart(2, "0");
        const yyyy  = String(d.getFullYear());

        let datePart;
        if (sequenceFormat === "mm/dd/yyyy") datePart = `${mm}${dd}${yyyy}`;
        else if (sequenceFormat === "yyyy/mm/dd") datePart = `${yyyy}${mm}${dd}`;
        else datePart = `${dd}${mm}${yyyy}`;  // default dd/mm/yyyy

        const paddedNo = String(nextIncrement).padStart(2, "0");
        const ginNo    = `${datePart}${paddedNo}`;

        setForm((p) => ({
          ...p,
          ginNo,
          ginDate:     today,
          challanDate: today,
          billDate:    today,
          ewayDate:    today,
        }));
      } catch (err) {
        /* Fallback: generate a temporary local code */
        console.error("Could not fetch document sequence:", err);
        const d      = new Date();
        const dd     = String(d.getDate()).padStart(2, "0");
        const mm     = String(d.getMonth() + 1).padStart(2, "0");
        const yyyy   = String(d.getFullYear());
        const ginNo  = `${dd}${mm}${yyyy}01`;
        setForm((p) => ({
          ...p,
          ginNo,
          ginDate:     today,
          challanDate: today,
          billDate:    today,
          ewayDate:    today,
        }));
      }
    };

    fetchGinNo();
  }, []);

  /* ── Default site once loaded ── */
  useEffect(() => {
    if (siteOptions.length > 0 && !form.site) {
      setForm((p) => ({ ...p, site: siteOptions[0].siteCode }));
    }
  }, [siteOptions]);

  /* ── Fetch Transaction Categories for Inventory → Inward ── */
  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const res = await axios.get(`${API_URL}/api/transactions`);
        const filtered = res.data.filter(
          (t) =>
            t.module === "Inventory" &&
            t.businessEntity === "Inward" &&
            t.status === "Open"
        );
        setTransactionCategories(filtered);
      } catch (err) {
        console.error("Failed to fetch transaction categories:", err);
      }
    };
    fetchCategories();
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((p) => ({ ...p, [name]: value }));
  };

  /* ── Items grid handlers ── */
  const handleItemChange = (rowIdx, field, value) => {
    setItems((prev) => {
      const next = [...prev];
      next[rowIdx] = { ...next[rowIdx], [field]: value };
      return next;
    });
  };

  const handleItemCheck = (rowIdx, checked) => {
    setItems((prev) => {
      const next = [...prev];
      next[rowIdx] = { ...next[rowIdx], _checked: checked };
      return next;
    });
  };

  const handleInsertRows = () => {
    const count = Math.max(1, Math.min(50, Number(insertCount) || 1));
    setItems((prev) => {
      const startSNo = prev.length + 1;
      const newRows  = Array.from({ length: count }, (_, i) => blankItem(startSNo + i));
      return [...prev, ...newRows];
    });
  };

  const handleDeleteChecked = () => {
    setItems((prev) => {
      const kept = prev.filter((r) => !r._checked);
      return kept.map((r, i) => ({ ...r, sNo: i + 1 }));
    });
  };

  /* ── Save ── */
  const handleSave = async () => {
    if (!form.ginDate)          { alert("GIN Date is required");           return; }
    if (!form.challanInvoiceNo) { alert("Challan/Invoice No is required"); return; }
    if (!form.site)             { alert("Please select a Site");           return; }

    try {
      setLoading(true);

      /* 1. Register a new sequence entry for Inventory / Inward */
      const seqRes = await axios.post(`${API_URL}/api/create-document-sequence`, {
        module:         "Inventory",
        businessEntity: "Inward",
        sequenceFormat: "dd/mm/yyyy",   // adjust if you store a preference
      });

      /* 2. Use the returned generatedCode as the official GIN No */
      const officialGinNo = seqRes.data.generatedCode;

      const cleanItems = items
        .filter((r) => {
          const { sNo, _checked, ...rest } = r;
          return Object.values(rest).some((v) => v !== "");
        })
        .map(({ _checked, ...r }) => r);

      const payload = { ...form, ginNo: officialGinNo, items: cleanItems };
      const res = await axios.post(`${API_URL}/api/goods-inward-note`, payload);
      if (res.data.success) {
        alert("Goods Inward Note Saved Successfully");
        navigate("/goods-inward-note");
      }
    } catch (err) {
      console.error(err);
      alert("Save Failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const anyChecked = items.some((r) => r._checked);

  return (
    <div className="cgin-page">
      <ModuleNavbar />

      {/* HEADER */}
      <div className="cgin-header">
        <div className="cgin-header-left">
          <button className="cgin-back-btn" onClick={() => navigate("/goods-inward-note")}>←</button>
          <h2>Create Goods Inward Note</h2>
        </div>
      </div>

      {/* FORM CARD */}
      <div className="cgin-card">
        <div className="cgin-section-title">GIN INFORMATION</div>

        <div className="cgin-grid">

          {/* GIN No — read-only, generated from DocumentSequence */}
          <div className="cgin-field">
            <label>GIN No</label>
            <input
              type="text"
              value={form.ginNo || "Generating…"}
              readOnly
              style={{ fontWeight: 600, letterSpacing: 1, color: "#15803d" }}
            />
          </div>

          <div className="cgin-field">
            <label>PO/CPO No</label>
            <input type="text" name="poCpoNo" value={form.poCpoNo}
              onChange={handleChange} placeholder="Enter PO/CPO No" />
          </div>

          <div className="cgin-field">
            <label>Status</label>
            <input type="text" value={form.status} readOnly />
          </div>

          {/* SITE */}
          <div className="cgin-field">
            <label>Site</label>
            <select name="site" value={form.site} onChange={handleChange} disabled={sitesLoading}>
              <option value="">{sitesLoading ? "Loading…" : "- Select Site -"}</option>
              {siteOptions.map((s) => (
                <option key={s._id} value={s.siteCode}>
                  {s.siteCode} — {s.siteName}
                </option>
              ))}
            </select>
          </div>

          <div className="cgin-field">
            <label>GIN Date</label>
            <input type="date" name="ginDate" value={form.ginDate} onChange={handleChange} />
          </div>

          <div className="cgin-field">
            <label>GIN Description</label>
            <input type="text" name="ginDescription" value={form.ginDescription}
              onChange={handleChange} placeholder="Enter description" />
          </div>

          <div className="cgin-field">
            <label>GIN Type</label>
            <select name="ginType" value={form.ginType} onChange={handleChange}>
              <option>Domestic</option>
              <option>Import</option>
            </select>
          </div>

          <div className="cgin-field">
            <label>Delivery Mode</label>
            <select name="deliveryMode" value={form.deliveryMode} onChange={handleChange}>
              <option>By Road</option>
              <option>By Rail</option>
              <option>By Air</option>
              <option>By Sea</option>
            </select>
          </div>

          {/* TRANSACTION CATEGORY */}
          <div className="cgin-field">
            <label>Transaction Category</label>
            <select name="transactionCategory" value={form.transactionCategory} onChange={handleChange}>
              <option value="">- Select -</option>
              {transactionCategories.map((t) => (
                <option key={t._id} value={t.transactionCategoryCode}>
                  {t.transactionCategoryCode} — {t.categoryDescription}
                </option>
              ))}
            </select>
          </div>

          <div className="cgin-field">
            <label>Vendor Code</label>
            <input type="text" name="vendorCode" value={form.vendorCode}
              onChange={handleChange} placeholder="Enter vendor code" />
          </div>

          <div className="cgin-field">
            <label>Vendor Name</label>
            <input type="text" name="vendorName" value={form.vendorName}
              onChange={handleChange} placeholder="Enter vendor name" />
          </div>

          <div className="cgin-field">
            <label>Manufacturer Address</label>
            <input type="text" name="manufacturerAddress" value={form.manufacturerAddress}
              onChange={handleChange} placeholder="Enter manufacturer address" />
          </div>

          <div className="cgin-field">
            <label>Vehicle Entry</label>
            <select name="vehicleEntry" value={form.vehicleEntry} onChange={handleChange}>
              <option>Inward</option>
              <option>Outward</option>
            </select>
          </div>

          <div className="cgin-field">
            <label>Manufacturer Code</label>
            <input type="text" name="manufacturerCode" value={form.manufacturerCode}
              onChange={handleChange} placeholder="Enter manufacturer code" />
          </div>

          <div className="cgin-field">
            <label>Manufacturer Name</label>
            <input type="text" name="manufacturerName" value={form.manufacturerName}
              onChange={handleChange} placeholder="Enter manufacturer name" />
          </div>

          <div className="cgin-field">
            <label>Vehicle No</label>
            <input type="text" name="vehicleNo" value={form.vehicleNo}
              onChange={handleChange} placeholder="Enter vehicle no" />
          </div>

          <div className="cgin-field">
            <label>Challan/Invoice No <span className="req">*</span></label>
            <input type="text" name="challanInvoiceNo" value={form.challanInvoiceNo}
              onChange={handleChange} placeholder="Enter challan/invoice no" className="inp-highlight" />
          </div>

          <div className="cgin-field">
            <label>Challan Date <span className="req">*</span></label>
            <input type="date" name="challanDate" value={form.challanDate}
              onChange={handleChange} className="inp-highlight" />
          </div>

          <div className="cgin-field">
            <label>Bill Date</label>
            <input type="date" name="billDate" value={form.billDate} onChange={handleChange} />
          </div>

          <div className="cgin-field">
            <label>E-Way Date</label>
            <input type="date" name="ewayDate" value={form.ewayDate} onChange={handleChange} />
          </div>

        </div>

        {/* REMARKS */}
        <div className="cgin-full-width">
          <div className="cgin-field">
            <label>Remarks</label>
            <textarea rows="3" name="remarks" value={form.remarks}
              onChange={handleChange} placeholder="Enter remarks..." />
          </div>
          <div className="cgin-field">
            <label>Comments</label>
            <textarea rows="3" name="comments" value={form.comments}
              onChange={handleChange} placeholder="Enter comments..." />
          </div>
        </div>

        {/* ITEMS GRID */}
        <div className="cgin-items-section">
          <div className="cgin-items-header">
            <span className="cgin-items-title">* Items</span>
            {anyChecked && (
              <button className="cgin-del-rows-btn" onClick={handleDeleteChecked}>
                Delete Selected
              </button>
            )}
          </div>

          <div className="cgin-items-table-wrap">
            <table className="cgin-items-table">
              <thead>
                <tr>
                  <th>S No</th>
                  <th>Insert Bags</th>
                  <th>Delete</th>
                  <th>Item Rate</th>
                  <th>Transaction No</th>
                  <th>Party Name</th>
                  <th>Broker</th>
                  <th>Item Code</th>
                  <th>Item Name</th>
                  <th>UOM</th>
                  <th>Sales Through</th>
                </tr>
              </thead>
              <tbody>
                {items.map((row, idx) => (
                  <tr key={idx} className={row._checked ? "cgin-row-checked" : ""}>
                    <td className="cgin-sno-cell">{row.sNo}</td>
                    <td>
                      <input type="text" className="cgin-item-input" value={row.insertBags}
                        onChange={(e) => handleItemChange(idx, "insertBags", e.target.value)} placeholder="Bags" />
                    </td>
                    <td className="cgin-check-cell">
                      <input type="checkbox" checked={row._checked}
                        onChange={(e) => handleItemCheck(idx, e.target.checked)} />
                    </td>
                    <td>
                      <input type="number" className="cgin-item-input cgin-item-num" value={row.itemRate}
                        onChange={(e) => handleItemChange(idx, "itemRate", e.target.value)} placeholder="0.00" />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input" value={row.transactionNo}
                        onChange={(e) => handleItemChange(idx, "transactionNo", e.target.value)} />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input cgin-item-wide" value={row.partyName}
                        onChange={(e) => handleItemChange(idx, "partyName", e.target.value)} />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input" value={row.broker}
                        onChange={(e) => handleItemChange(idx, "broker", e.target.value)} />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input" value={row.itemCode}
                        onChange={(e) => handleItemChange(idx, "itemCode", e.target.value)} />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input cgin-item-wide" value={row.itemName}
                        onChange={(e) => handleItemChange(idx, "itemName", e.target.value)} />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input cgin-item-sm" value={row.uom}
                        onChange={(e) => handleItemChange(idx, "uom", e.target.value)} placeholder="MT" />
                    </td>
                    <td>
                      <input type="text" className="cgin-item-input" value={row.salesThrough}
                        onChange={(e) => handleItemChange(idx, "salesThrough", e.target.value)} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="cgin-insert-row-bar">
            <input type="number" min="1" max="50" className="cgin-insert-count"
              value={insertCount} onChange={(e) => setInsertCount(e.target.value)} />
            <button className="cgin-insert-row-btn" onClick={handleInsertRows}>
              Insert Row
            </button>
          </div>
        </div>

        {/* ACTIONS */}
        <div className="cgin-actions">
          <button className="btn-cancel" onClick={() => navigate("/goods-inward-note")} disabled={loading}>
            Cancel
          </button>
          <button className="btn-save" onClick={handleSave} disabled={loading}>
            {loading ? "Saving…" : "Save"}
          </button>
        </div>
      </div>
    </div>
  );
};

export default CreateGIN;